spring.datasource.url=jdbc:postgresql://localhost:5432/livescore
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=West5555

spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ericemeka732@gmail.com
spring.mail.password=ssqybanzlmrzimck
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=ericemeka732@gmail.com
app.frontend-url=http://localhost:3000

app.jwt.secret=3I8jm5wOWUs3gTuigFTe1XipKWfJXgjYG9g3UAI0Xew=
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000